language: node_js
node_js:
  - '5.1'

env:
  global:
    secure: "Azu52+ABOHix9dTGlKIfwzZ0v/CYoRRMwYTfKwb43crhpfvGh97vnNLzrGwuvVHIYzvmra1IUtzi6WkFFBi46alrgOsHrhphlctXVSNxPwsd2EkJoA9yPvtbTf2wb2OF0qIF5zBAXs9rtmN9hpmi8Qs2/a7QAcROVA1uC2zn/uYfmxhWq19iBGhggQ1WX/zsdz8g2RO1c5z3vePTfQUYVGL0AFNX4nZdKBKw+iS0HimhTC9nuHTf/s7hOUl/bQVI09/vb4/90g9/oOOsnTpWIc84P19Cdq9nh0L5rMwFuPzb9BQpvisS19FzA1dFsNjH6JJW/nPKDDLFiJcmE0trlKlNI2LSkZ3U14imkB7UL8Rd0qy1ojGVKEjd05fWev3PFqQP2EnTgzpZrq1/+wX3V5f6vVH7ghH0WoVVsTPWR4kaRsiSWHfarDVfeX20Zij8jsJbY8E6x24K17DCvGR9ILRyETqWDR4G4mGUPJDPCBCjNTNIfrEOcYZs1euU1vQq3JSrVHbHMT7ZBCT47SZGNXPZBHRhT34VRi8fWzUVwr1YiNP8fkF5dltGiTXvdH7EZG+DK9aXl40EqJLr0zMyq9NYoUpqh1w3098yR4l9XXqIOCZS3/4a1AsmhGl+DHI6F4gDTWzZJo4r/ljbEp5MEcHpSt8VFcWKmfKckkjaQQw="

before_install:
  - npm install -g typings
  - npm install -g webpack

install:
  - npm install

script: npm run dist

after_success:
  - "./deploy.sh"
